version: '3.8'

services:

  api_rastreabilidade:
   container_name: api_rastreabilidade
   build: .
   restart: always
   command: bash -c "npm install && npx prisma generate && npm run build && npm run start"
   env_file:
      - .env
   environment:
    - TZ=America/Manaus
   volumes: 
     - ./:/usr/app
   ports: 
     - 7401:7400
  database:
    image: postgres
    depends_on: 
    - api_rastreabilidade
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=00bfc8c729f5d4d529a412b12c58ddd2
      - POSTGRES_DB=sdrtcp
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
