version: '3.8'

services:

  api_rastreabilidade:
   container_name: api_rastreabilidade
   build: .
   restart: always
   command: bash -c "npm install && npx prisma generate && npx prisma db push && npm run dev"
   environment:
    - TZ=America/Manaus
   volumes: 
     - ./:/usr/app
   ports: 
     - 15000:7400

  database:
    image: postgres
    depends_on: 
    - api_rastreabilidade
    container_name: database
    restart: always
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=00bfc8c729f5d4d529a412b12c58ddd2
      - POSTGRES_DB=sdrtcp
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
